name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: git-hydra

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux/$EXPORT_NAME
          godot -v --export "Linux" build/linux/$EXPORT_NAME/$EXPORT_NAME.x86_64
          cd build/linux
          zip -r $EXPORT_NAME.zip $EXPORT_NAME
          rm $EXPORT_NAME -rf
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OS" build/mac/$EXPORT_NAME.zip
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true 

